language: go
go:
  - "1.13"

branches:
  only:
  - master

services:
  - docker

env:
  - GOFLAGS=-mod=vendor

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

script:
  - make test
  - make vet
  - make website-test
